### ISSUE TITLE
[rawhide] `ext.config.extensions.module` failing due to missing modular packages

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1104]
**Describe the bug**

```
Feb 14 16:45:20 qemu0 kola-runext-module[1628]: Enabled rpm-md repositories: fedora-cisco-openh264 rawhide-modular rawhide
Feb 14 16:45:22 qemu0 kola-runext-module[1628]: Updating metadata for 'fedora-cisco-openh264'...done
Feb 14 16:45:22 qemu0 kola-runext-module[1628]: Updating metadata for 'rawhide-modular'...done
Feb 14 16:45:29 qemu0 kola-runext-module[1628]: Updating metadata for 'rawhide'...done
Feb 14 16:46:06 qemu0 kola-runext-module[1628]: Importing rpm-md...done
Feb 14 16:46:06 qemu0 kola-runext-module[1628]: rpm-md repo 'fedora-cisco-openh264'; generated: 2021-09-22T15:57:13Z solvables: 4
Feb 14 16:46:06 qemu0 kola-runext-module[1628]: rpm-md repo 'rawhide-modular'; generated: 2022-02-13T07:23:22Z solvables: 17
Feb 14 16:46:06 qemu0 kola-runext-module[1628]: rpm-md repo 'rawhide'; generated: 2022-02-14T05:56:00Z solvables: 67802
Feb 14 16:46:06 qemu0 kola-runext-module[1628]: error: Installing modules: Problems appeared for module install request:
Feb 14 16:46:06 qemu0 kola-runext-module[1628]:   - Unable to resolve argument 'nginx:mainline'
Feb 14 16:46:06 qemu0 kola-runext-module[1628]:   - Unable to resolve argument 'cri-o:1.22/default'
```

**Additional information**

I think these just need a rebuild.

**Comment by jlebon** [comment]
Was going to make PRs for this, but I think it's just really pushing an empty commit does the trick:

https://src.fedoraproject.org/modules/nodejs/c/f8200a9b6565686c698af8548e06070db2e1ca99?branch=16

@haircommander Do you want to do that for cri-o?

**Comment by haircommander** [comment]
done!

**Comment by dustymabe** [comment]
I still see both `nginx` and `cri-o` failing if I run this test today:

```
Feb 28 15:19:28 qemu0 kola-runext-module[1646]: + rpm-ostree ex module install cri-o:1.22/default nginx:mainline
Feb 28 15:19:28 qemu0 kola-runext-module[1647]: NOTICE: Experimental commands are subject to change.
Feb 28 15:19:31 qemu0 kola-runext-module[1647]: Checking out tree ce33588...done
Feb 28 15:19:31 qemu0 kola-runext-module[1647]: Enabled rpm-md repositories: fedora-cisco-openh264 rawhide-modular rawhide
Feb 28 15:19:33 qemu0 kola-runext-module[1647]: Updating metadata for 'fedora-cisco-openh264'...done
Feb 28 15:19:34 qemu0 kola-runext-module[1647]: Updating metadata for 'rawhide-modular'...done
Feb 28 15:19:37 qemu0 kola-runext-module[1647]: Updating metadata for 'rawhide'...done
Feb 28 15:19:52 qemu0 kola-runext-module[1647]: Importing rpm-md...done
Feb 28 15:19:52 qemu0 kola-runext-module[1647]: rpm-md repo 'fedora-cisco-openh264'; generated: 2021-09-22T15:57:13Z solvables: 4
Feb 28 15:19:52 qemu0 kola-runext-module[1647]: rpm-md repo 'rawhide-modular'; generated: 2022-02-27T07:15:25Z solvables: 268
Feb 28 15:19:52 qemu0 kola-runext-module[1647]: rpm-md repo 'rawhide'; generated: 2022-02-28T07:15:27Z solvables: 67798
Feb 28 15:19:52 qemu0 kola-runext-module[1647]: error: Installing modules: Problems appeared for module install request:
Feb 28 15:19:52 qemu0 kola-runext-module[1647]:   - Unable to resolve argument 'nginx:mainline'
Feb 28 15:19:52 qemu0 kola-runext-module[1647]:   - Unable to resolve argument 'cri-o:1.22/default'
Feb 28 15:19:52 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 15:19:52 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
```

cc @jlebon @haircommander

**Comment by dustymabe** [comment]
The snooze for `ext.config.extensions.module` was extended in https://github.com/coreos/fedora-coreos-config/pull/1543.

**Comment by dustymabe** [comment]
The snooze for `ext.config.extensions.module` was extended in https://github.com/coreos/fedora-coreos-config/pull/1576.

**Comment by dustymabe** [comment]
I think this is passing now!
