### ISSUE TITLE
[rawhide]: Podman fails with pasta networking

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1509]
### Describe the bug

Using the latest `passt-0^20230603.g429e1a7-1.fc39`, we run a podman basic test that uses pasta network and sets the gateway. The test fails to download from the internet after we run `podman run`.

The upgrade of passt packages that caused it: `passt 0^20230509.g96f8d55-1.fc39 -> 0^20230603.g429e1a7-1.fc39`

```
[2023-06-04T15:43:12.304Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: # Download something from the internet. Here we use one of the test
[2023-06-04T15:43:12.304Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: # fixtures from the ignition.resource.remote test.
[2023-06-04T15:43:12.304Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: result=$(curl https://ignition-test-fixtures.s3.amazonaws.com/resources/anonymous)
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: [ "$result" == "kola-anonymous" ] || exit 1
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: EOF
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: '
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: + chmod +x /tmp/tmp.nuLKsZvfT3runascoreuser
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: + chown core /tmp/tmp.nuLKsZvfT3runascoreuser
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4544]: + runascoreuser /tmp/tmp.nuLKsZvfT3runascoreuser
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4549]: + cat
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 kola-runext-rootless-pasta-networking[4548]: + sudo -u core /tmp/tmp.nuLKsZvfT3runascoreuser
[2023-06-04T15:43:12.305Z] Jun 04 15:43:06 qemu0 sudo[4548]:     root : PWD=/ ; USER=core ; COMMAND=/tmp/tmp.nuLKsZvfT3runascoreuser
[2023-06-04T15:43:12.305Z] Jun 04 15:43:11 qemu0 kola-runext-rootless-pasta-networking[4544]: + fatal 'Podman with pasta networking failed'
[2023-06-04T15:43:12.305Z] Jun 04 15:43:11 qemu0 kola-runext-rootless-pasta-networking[4544]: + echo 'Podman with pasta networking failed'
[2023-06-04T15:43:12.305Z] Jun 04 15:43:11 qemu0 kola-runext-rootless-pasta-networking[4544]: Podman with pasta networking failed
[2023-06-04T15:43:12.305Z] Jun 04 15:43:11 qemu0 kola-runext-rootless-pasta-networking[4544]: + exit 1
```

### System details

[rawhide][x86_64] ⚡ 39.20230604.91.0

BZ Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2213280

**Comment by gursewak1997** [comment]
This issue was also seen in Fedora 38.
Pinned previous version in [Rawhide](https://github.com/coreos/fedora-coreos-config/pull/2455)
Pinned previous version in [testing-devel
](https://github.com/coreos/fedora-coreos-config/pull/2457)
Testing-devel pipeline [run](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/bump-lockfile/602/)

**Comment by dustymabe** [comment]
Some more information:

```
09:23:08        dustymabe | sbrivio: we've been having an issue with the new RPM for pasta networking in FCOS:
                          | https://github.com/coreos/fedora-coreos-tracker/issues/1509
09:24:10        dustymabe | It's failing on this test: https://github.com/coreos/fedora-coreos-config/blob/testi
                          | ng-devel/tests/kola/podman/rootless-pasta-networking 
09:24:19        dustymabe | any ideas what could be going wrong? 
09:46:28 PaulHolzinger[m] | dustymabe: I didn't took a deep look but it looks like the same as
                          | https://github.com/containers/podman/pull/18612#issuecomment-1602260839
09:47:18 PaulHolzinger[m] | which should be fixed with
                          | https://archives.passt.top/passt-dev/20230622224300.2030886-1-sbrivio@redhat.com/
09:52:11        dustymabe | PaulHolzinger[m]: nice. I can't tell - is that commit merged and/or in a release?
09:52:46 PaulHolzinger[m] | not merged
```

**Comment by sbrivio-rh** [comment]
My bad. I'll update this ticket once a new version of the Fedora package fixes this (in approximately one day).

**Comment by sbrivio-rh** [comment]
Fixed in [`passt-0^20230625.g32660ce-1.fc39`](https://bodhi.fedoraproject.org/updates/FEDORA-2023-cf99684fe2).

**Comment by gursewak1997** [comment]
@sbrivio-rh It looks like the test is still failing in the above package update.

**Comment by dustymabe** [comment]
The test script is [here](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/podman/rootless-pasta-networking). @sbrivio-rh Is the test somehow invalid?

**Comment by sbrivio-rh** [comment]
> @sbrivio-rh It looks like the test is still failing in the above package update.

Ouch, sorry. Where does it fail exactly? Can you share the output?

> The test script is [here](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/podman/rootless-pasta-networking). @sbrivio-rh Is the test somehow invalid?

I just had a quick look when it was introduced but I didn't really review it :( One thing that occurs to me now is that `-g 8.8.8.8` actually assigns 8.8.8.8 as the default gateway in the container, but no matching address (on the same subnet) is configured, so we can't actually send traffic (but it worked before...? I'm puzzled).

I would suggest either dropping the `-g,8.8.8.8` option, or adding a matching address to the container and using either private network addressing (such as `-a,10.0.0.1,-g,10.0.0.2`) or addresses from a `TEST-NET` block (`-a,192.0.2.1,-g,192.0.2.2`)
