### ISSUE TITLE
Installation on qemu with multipath fails

### ISSUE THREAD

**Issue by nikita-dubrovskii** [coreos/fedora-coreos-tracker#531]
I've been trying to install FCOS on qemu + multipath (using kargs: `coreos.inst=yes multipath=default rd.multipath=on coreos.inst.install_dev=/dev/mapper/mpatha`) and got an error: `no such device`

Despite [https://github.com/coreos/fedora-coreos-config/pull/392/commits/2a37f64a37aed8d4e9568a11b9a43a41ba17473f](url) includes multipathd, without config daemon doesn't create any DM-device.

**Comment by lucab** [comment]
I've moved this to the usual FCOS bug tracker. @darkmuggle for reference, what's the version of the Dracut package with the fix?

**Comment by darkmuggle** [comment]
Drauct 050-61.git20200529.fc32.x86_64
https://github.com/coreos/fedora-coreos-config/commit/e9448fe108fd6dcca279fee3281f0eebd3076ca9#diff-ff3513bf31ba6384ab3733e797bed52eL204-L206

https://koji.fedoraproject.org/koji/buildinfo?buildID=1517388 which includes
https://src.fedoraproject.org/rpms/dracut/blob/308914b60e6809c6b644ba4d11eb11a769491019/f/0033.patch

**Comment by dustymabe** [comment]
> Drauct 050-61.git20200529.fc32.x86_64
> [coreos/fedora-coreos-config@e9448fe#diff-ff3513bf31ba6384ab3733e797bed52eL204-L206](https://github.com/coreos/fedora-coreos-config/commit/e9448fe108fd6dcca279fee3281f0eebd3076ca9#diff-ff3513bf31ba6384ab3733e797bed52eL204-L206)

which means our latest `testing` build (` 32.20200601.2.1`) should have it.

**Comment by dustymabe** [comment]
@nikita-dubrovskii - can you confirm the problem is fixed now?

**Comment by nikita-dubrovskii** [comment]
Thx, installation works! Still have some issues during firstboot ( `coreos-boot-mount-generator: line 52: cannot create temp file for here-document: Read-only file system`), but that seems to be related to qemu. Later will test on s390x

**Comment by dustymabe** [comment]
Thanks @nikita-dubrovskii. FYI for future people who stumble opon this ticket:

The fix for this went into testing stream release `32.20200601.2.1`.

**Comment by darkmuggle** [comment]
@nikita-dubrovskii Thank you for your patience as we fleshed out multipath. Personally, I appreciate your proposed patch and testing things out.

**Comment by nikita-dubrovskii** [comment]
As a small hint for others who want multipath starting from `firstboot`:
add `rd.multipath=default root=/dev/disk/by-label/dm-mpath-root rw` to kernel parameters and after system is booted make those options persistent:
`sudo rpm-ostree kargs --append=rd.multipath=default`
`sudo rpm-ostree kargs --append=root=/dev/disk/by-label/dm-mpath-root `
`sudo rpm-ostree kargs --append=rw`
`sudo reboot`

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20200601.3.0`.
