### ISSUE TITLE
tracker for podman 2.x progress

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#575]
In https://github.com/coreos/fedora-coreos-tracker/issues/560 we elected to pin podman 1.9.3 in our `testing` and `stable` streams for now. This ticket will serve as a tracker for existing issues with podman 2.x that could or should block 2.x from hitting `testing`/`stable`.

- https://github.com/containers/podman/pull/6842 (suggested by @jdoss)
- https://github.com/containers/podman/issues/6734 (suggested by @dustymabe)
- https://github.com/containers/podman/issues/6879 (suggested by @travier)
- https://github.com/containers/podman/issues/7441 (suggested by @dustymabe)

**Comment by dustymabe** [comment]
FYI: If you'd like to test out podman 2.x to find if your containers still work we have docs on how to [switch between streams]( https://docs.fedoraproject.org/en-US/fedora-coreos/update-streams/#_switching_to_a_different_stream). You should target `next`.

**Comment by dustymabe** [comment]
https://github.com/containers/podman/issues/6734 is closed now with the fix in https://github.com/containers/podman/pull/7339. This landed in the 2.0.5 release with https://github.com/containers/podman/commit/ce1389b:

```
[dustymabe@media podman ((v2.0.5))]$ git tag --contains ce1389b
v2.0.5
```

I'll try to verify this fixes the problem I was seeing at least.

**Comment by travier** [comment]
I had https://github.com/containers/podman/issues/6879 opened for podman 2.0 but this should be fixed now with 2.0.5.

**Comment by dustymabe** [comment]
> I had [containers/podman#6879](https://github.com/containers/podman/issues/6879) opened for podman 2.0 but this should be fixed now with 2.0.5.

Added it to the list in the description. Thanks!

**Comment by dustymabe** [comment]
I just opened https://github.com/containers/podman/issues/7441 and added it to the list. Running systemd in a rootless container still does not work.

**Comment by dustymabe** [comment]
The fix for https://github.com/containers/podman/issues/7441 has been backported to podman 2.0.6 and I've confirmed it seems to fix the problem. I'm thinking that we should get that into `next-devel` as soon as there is an rpm available for 2.0.6 and then do an `ad-hoc` `next` release this week.

Then we could switch over `testing` in next week's round of releases.

**Comment by dustymabe** [comment]
Today's `next` stream release (32.20200901.1.0) includes podman 2.0.6, which should fix all outstanding issues mentioned in this ticket. If all goes well it will landing in `testing` next week. Please give the `next` stream a spin and report issues!

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20200907.2.0`. Please try out the new release and report issues.

**Comment by zyclonite** [comment]
@dustymabe could below error be related to that upgrade?

`podman[]: Error: requested OCI runtime runc is not compatible with NoCgroups: invalid argument`

we are running containers in a systemd unit with `--name %N --conmon-pidfile %t/%N.pid --cgroups disabled --log-driver journald` so systemd has always control over the process (also following shutdown order)

should `cgroups disabled` still work?

tested on the current `32.20200907.*` releases

**Comment by dustymabe** [comment]
hey @zyclonite - can you open a new issue for this and we can discuss it more there? When you open the new issue can you mention what version you were upgrading from that your systemd unit worked in?

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20200907.3.0`.

**Comment by zyclonite** [comment]
@dustymabe did that now, added already our findings as well https://github.com/coreos/fedora-coreos-tracker/issues/634
